use_frameworks!

platform :ios, '9.0'

target 'ReactiveEureka_Example' do
  pod 'ReactiveEureka', :path => '../'

  target 'ReactiveEureka_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1'
  	pod 'Nimble', '~> 7'
  	pod 'FBSnapshotTestCase'
  	pod 'Nimble-Snapshots'
  end
end
